// Generated by CoffeeScript 1.7.1
(function() {
  var UserService;

  UserService = require('../../src/service/UserService');

  module.exports = {
    "UserService-save-test": function(test) {
      var user;
      test.expect(1);
      user = {
        name: 'ice'
      };
      return UserService.save(user, function(uid) {
        test.equals(uid, 123);
        return test.done();
      });
    },
    "UserService-find-test": function(test) {
      var uid;
      test.expect(1);
      uid = 123;
      return UserService.find(uid, function(user) {
        test.equals(user.name, 'ice');
        return test.done();
      });
    }
  };

}).call(this);
