// Generated by CoffeeScript 1.7.1
(function() {
  var User;

  User = require('../../src/model/User');

  module.exports = {
    "save user test": function(test) {
      var user;
      test.expect(1);
      user = {
        name: 'ice'
      };
      return User.save(user, function(uid) {
        test.equals(uid, 123);
        return test.done();
      });
    },
    "find user test": function(test) {
      var uid;
      test.expect(1);
      uid = 123;
      return User.find(uid, function(user) {
        test.equals(user.name, 'ice');
        return test.done();
      });
    }
  };

}).call(this);
