// Generated by CoffeeScript 1.7.1
(function() {
  var UserDao;

  UserDao = require('../model/User');

  module.exports = {
    save: function(user, cb) {
      return UserDao.save(user, function(uid) {
        return cb(uid);
      });
    },
    find: function(uid, cb) {
      return UserDao.find(uid, function(user) {
        return cb(user);
      });
    }
  };

}).call(this);
