// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    save: function(user, cb) {
      var uid;
      uid = 123;
      return cb(uid);
    },
    find: function(uid, cb) {
      var user;
      user = {
        uid: 123,
        name: 'ice'
      };
      return cb(user);
    }
  };

}).call(this);
